//! Emits the shared FOV fixture consumed by BOTH test suites (D31).
//!
//! The formula in docs/03 §7 is implemented twice — `Player::compute_fov` and
//! `client/src/logic/fov.ts` — which is a drift hazard of exactly the kind
//! docs/06 warns about for the protocol. Rather than trusting two hand-written
//! test tables to stay in step, the Rust implementation generates the vectors
//! and the TypeScript test asserts against the same file.
//!
//! Regenerate when the formula changes deliberately:
//!   cargo run -p game-core --example fov_vectors
use game_core::player::Player;
use std::path::Path;

/// Inputs to sample. Mirrors `player::fov_tests::FOV_VECTORS`.
const CASES: [(f32, bool, f32, bool); 12] = [
    (0.0, false, 100.0, false),
    (1.0, false, 100.0, false),
    (0.5, false, 100.0, false),
    (0.0, true, 100.0, false),
    (0.0, false, 49.0, false),
    (0.0, false, 50.0, false),
    (1.0, true, 100.0, false),
    (1.0, false, 10.0, false),
    (1.0, true, 10.0, false),
    (1.0, false, 100.0, true),
    (1.0, true, 100.0, true),
    (1.0, false, 10.0, true),
];

fn main() {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"_comment\": \"Generated by game-core/examples/fov_vectors.rs. Do not hand-edit. Asserted by BOTH server (player::fov_tests) and client (logic/fov.test.ts) so the two implementations of docs/03 §7 cannot drift.\",\n");
    out.push_str("  \"vectors\": [\n");
    for (i, (day_phase, fog, health, flashlight)) in CASES.iter().enumerate() {
        let fov = Player::compute_fov(*day_phase, *fog, *health, *flashlight);
        out.push_str(&format!(
            "    {{ \"day_phase\": {day_phase}, \"fog_active\": {fog}, \"health\": {health}, \"flashlight\": {flashlight}, \"fov\": {fov} }}{}\n",
            if i + 1 == CASES.len() { "" } else { "," }
        ));
    }
    out.push_str("  ]\n}\n");

    // Written into the CLIENT tree: the client is the consumer that would
    // otherwise drift. Path resolved from CARGO_MANIFEST_DIR so cwd is
    // irrelevant.
    let target = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../client/src/logic/fov-vectors.json");
    std::fs::write(&target, &out).expect("writing the FOV fixture");
    eprintln!("wrote {}", target.display());
}
