/**
 * Field-of-view radius (T2.10 step 3, docs/03 §7).
 *
 * A mirror of `Player::compute_fov` in `game-core/src/player.rs`. docs/08 §3
 * requires the client compute "the same formula as server — a copy of the
 * math", so the two are pinned to a shared fixture generated by the Rust
 * side (`fov-vectors.json`); see DEVIATIONS.md D31. Change one, regenerate,
 * and the other's test fails until it matches.
 */

/** Base FOV radius, px (docs/03 §7). */
export const FOV_BASE = 420;
/** Night multiplier at full night (docs/03 §7). */
export const FOV_NIGHT_MIN = 0.45;
/** Heavy-fog multiplier (docs/03 §7, docs/02 §6). */
export const FOV_FOG = 0.45;
/** Low-health multiplier (docs/03 §7). */
export const FOV_LOW_HEALTH_FACTOR = 0.7;
/** Health at or above which there is no penalty (docs/03 §7). */
export const FOV_LOW_HEALTH = 50;

/** Clamp to [0, 1]. */
function clamp01(t: number): number {
  if (t < 0) return 0;
  if (t > 1) return 1;
  return t;
}

/**
 * FOV radius in px.
 *
 * `fov = 420 * night_factor * fog_factor * health_factor`, where a flashlight
 * forces `night_factor` to 1.0 for its holder.
 */
export function computeFov(
  dayPhase: number,
  fogActive: boolean,
  health: number,
  flashlight: boolean,
): number {
  const nightFactor = flashlight
    ? 1.0
    : 1.0 + (FOV_NIGHT_MIN - 1.0) * clamp01(dayPhase);
  const fogFactor = fogActive ? FOV_FOG : 1.0;
  const healthFactor = health >= FOV_LOW_HEALTH ? 1.0 : FOV_LOW_HEALTH_FACTOR;
  return FOV_BASE * nightFactor * fogFactor * healthFactor;
}
