#!/usr/bin/env bash
#
# Test inventory guard.
#
# Deleting a test only ever makes the suite greener, so no gate notices it.
# This happened for real: commit 0decceb removed
# `surface_conversion_leaves_buried_dirt_alone` as a side effect of a
# slice-based edit, and the full gate stayed green while the negative half of
# docs/01 §5's conversion rule went unguarded.
#
# The fix is not to make deletion impossible — it is to make it impossible to do
# SILENTLY. The full list of test names is committed to tests-inventory.txt.
# Removing a test now shows up as a deleted line in the diff, which review sees,
# exactly like the golden map anchors.
#
#   ./scripts/test-inventory.sh check     # fail if the inventory is stale (gate)
#   ./scripts/test-inventory.sh update    # regenerate after an INTENTIONAL change
#
# Regenerating is fine. Regenerating without reading the removed lines is not.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INVENTORY="$ROOT/tests-inventory.txt"

generate() {
  echo "# Generated by scripts/test-inventory.sh — do not hand-edit."
  echo "# A deleted line here means a test was removed. That must be deliberate."
  echo
  echo "## rust"
  (
    cd "$ROOT/server"
    # --list prints "path::to::test: test"; keep the name, drop the suffix.
    cargo test --workspace -- --list 2>/dev/null \
      | grep ': test$' \
      | sed 's/: test$//' \
      | sort -u
  )
  echo
  echo "## typescript"
  (
    cd "$ROOT/client"
    npx vitest list 2>/dev/null | sort -u
  )
}

case "${1:-check}" in
  update)
    generate > "$INVENTORY"
    echo "wrote $INVENTORY ($(grep -cv '^\s*\(#\|$\)' "$INVENTORY") tests)"
    ;;
  check)
    if [[ ! -f "$INVENTORY" ]]; then
      echo "FAIL: $INVENTORY missing. Run: ./scripts/test-inventory.sh update" >&2
      exit 1
    fi
    if diff -u "$INVENTORY" <(generate) > /tmp/test-inventory.diff 2>&1; then
      echo "test inventory OK ($(grep -cv '^\s*\(#\|$\)' "$INVENTORY") tests)"
    else
      echo "FAIL: the test inventory is stale." >&2
      echo >&2
      sed -n '3,200p' /tmp/test-inventory.diff >&2
      echo >&2
      echo "Lines starting '-' are tests that NO LONGER EXIST. If that is" >&2
      echo "intentional, say why in the commit message and run:" >&2
      echo "  ./scripts/test-inventory.sh update" >&2
      exit 1
    fi
    ;;
  *)
    echo "usage: $0 [check|update]" >&2
    exit 2
    ;;
esac
