// Generated by dump-mockup.mjs from tasks/M23/reference/mockup-src — do not edit; re-run it.
import type { SceneData } from '../scene'
import { arenaE } from './arenaE.mask'

export const F2: SceneData = {
 "id": "F2",
 "title": "volcanic night",
 "theme": "volcanic",
 "camera": {
  "x": 0,
  "y": 0,
  "w": 1280,
  "h": 720
 },
 "mask": arenaE,
 "look": {
  "fogBack": {
   "color": [
    0.3,
    0.08,
    0.03
   ],
   "y0": 380,
   "y1": 540,
   "k": 0.6
  },
  "fogFront": {
   "color": [
    0.25,
    0.06,
    0.02
   ],
   "y0": 600,
   "y1": 720,
   "k": 0.4,
   "seed": 5
  },
  "fg": {
   "tint": [
    0.006,
    0.003,
    0.003
   ],
   "spots": [
    {
     "x": -10,
     "y": 560,
     "r": 90,
     "n": 9
    },
    {
     "x": 1300,
     "y": 700,
     "r": 110,
     "n": 10
    }
   ]
  },
  "bg": {
   "skyTop": 722695,
   "skyBottom": 3020562,
   "haze": 4464666,
   "horizon": 500,
   "grainK": 0.025,
   "glowY": 500,
   "glowColor": 2755076,
   "layers": [
    {
     "shape": "mesa",
     "x": 1000,
     "y": 120,
     "slope": 0.9,
     "top": 60,
     "color": 3350557,
     "step": 6,
     "soft": 2.8,
     "fade": [
      200,
      490,
      0.5
     ],
     "jitter": 1.1
    },
    {
     "shape": "zig",
     "x": 300,
     "y": 180,
     "slope": 0.9,
     "top": 50,
     "color": 2562070,
     "step": 7,
     "soft": 1.8,
     "fade": [
      240,
      495,
      0.5
     ],
     "jitter": 0.6
    },
    {
     "shape": "pyramid",
     "x": 820,
     "y": 170,
     "slope": 1.2,
     "color": 2035726,
     "step": 5,
     "soft": 1,
     "fade": [
      260,
      500,
      0.55
     ],
     "jitter": 0.9
    }
   ]
  },
  "lights": [
   {
    "x": 1115,
    "y": 515,
    "z": 70,
    "r": 460,
    "rgb": "255,140,50",
    "i": 3.2
   },
   {
    "x": 550,
    "y": 343,
    "z": 30,
    "r": 170,
    "rgb": "40,200,255",
    "i": 2.4
   },
   {
    "x": 526,
    "y": 340,
    "z": 30,
    "r": 120,
    "rgb": "255,200,110",
    "i": 1.8
   },
   {
    "x": 381,
    "y": 296,
    "z": 20,
    "r": 100,
    "rgb": "255,140,50",
    "i": 1.3
   },
   {
    "x": 910,
    "y": 289,
    "z": 20,
    "r": 120,
    "rgb": "255,140,50",
    "i": 1.5
   },
   {
    "x": 1181,
    "y": 472,
    "z": 20,
    "r": 150,
    "rgb": "255,140,50",
    "i": 2
   },
   {
    "x": 110,
    "y": 309,
    "z": 30,
    "r": 150,
    "rgb": "255,190,120",
    "i": 1.6
   },
   {
    "x": 250,
    "y": 334,
    "z": 20,
    "r": 110,
    "rgb": "255,90,40",
    "i": 1.2
   },
   {
    "x": 1110,
    "y": 215,
    "z": 20,
    "r": 100,
    "rgb": "255,90,40",
    "i": 1
   },
   {
    "x": 735,
    "y": 543,
    "z": 8,
    "r": 40,
    "rgb": "255,60,30",
    "i": 0.5
   }
  ],
  "bloom": [
   0.65,
   0.5,
   0.68
  ],
  "grade": {
   "vignette": 0.6,
   "sat": 1.05
  },
  "exposure": 1.1,
  "terrain": {
   "scorch": [
    {
     "x": 1120,
     "y": 548,
     "r": 80
    }
   ],
   "sunDir": [
    -0.3,
    -0.5,
    0.5
   ],
   "sunCol": [
    0.35,
    0.1,
    0.03
   ],
   "sky": [
    0.04,
    0.025,
    0.02
   ],
   "ground": [
    0.12,
    0.03,
    0.01
   ],
   "rimCol": [
    1,
    0.35,
    0.1
   ],
   "rimK": 0.45,
   "lipK": 0.08,
   "lipCol": [
    0.9,
    0.5,
    0.35
   ],
   "interior": 0.5,
   "bevel": 14,
   "lava": [
    1.6,
    0.45,
    0.08
   ],
   "lavaK": 0.6
  },
  "moon": {
   "dx": 0.2,
   "dy": 1,
   "rgb": "255,120,60",
   "w": 0.65,
   "fill": "120,60,50"
  }
 },
 "palette": {
  "theme": "volcanic",
  "timer": "1:34",
  "bg": {
   "skyTop": 722695,
   "skyBottom": 3020562,
   "haze": 4464666,
   "horizon": 500,
   "grainK": 0.025,
   "glowY": 500,
   "glowColor": 2755076,
   "layers": [
    {
     "shape": "mesa",
     "x": 1000,
     "y": 120,
     "slope": 0.9,
     "top": 60,
     "color": 3350557,
     "step": 6,
     "soft": 2.8,
     "fade": [
      200,
      490,
      0.5
     ],
     "jitter": 1.1
    },
    {
     "shape": "zig",
     "x": 300,
     "y": 180,
     "slope": 0.9,
     "top": 50,
     "color": 2562070,
     "step": 7,
     "soft": 1.8,
     "fade": [
      240,
      495,
      0.5
     ],
     "jitter": 0.6
    },
    {
     "shape": "pyramid",
     "x": 820,
     "y": 170,
     "slope": 1.2,
     "color": 2035726,
     "step": 5,
     "soft": 1,
     "fade": [
      260,
      500,
      0.55
     ],
     "jitter": 0.9
    }
   ]
  },
  "terrain": {
   "sunDir": [
    -0.3,
    -0.5,
    0.5
   ],
   "sunCol": [
    0.35,
    0.1,
    0.03
   ],
   "sky": [
    0.04,
    0.025,
    0.02
   ],
   "ground": [
    0.12,
    0.03,
    0.01
   ],
   "rimCol": [
    1,
    0.35,
    0.1
   ],
   "rimK": 0.45,
   "lipK": 0.08,
   "lipCol": [
    0.9,
    0.5,
    0.35
   ],
   "interior": 0.5,
   "bevel": 14,
   "lava": [
    1.6,
    0.45,
    0.08
   ],
   "lavaK": 0.6
  },
  "fogBack": {
   "color": [
    0.3,
    0.08,
    0.03
   ],
   "y0": 380,
   "y1": 540,
   "k": 0.6
  },
  "fogFront": {
   "color": [
    0.25,
    0.06,
    0.02
   ],
   "y0": 600,
   "y1": 720,
   "k": 0.4,
   "seed": 5
  },
  "fg": {
   "tint": [
    0.006,
    0.003,
    0.003
   ],
   "spots": [
    {
     "x": -10,
     "y": 560,
     "r": 90,
     "n": 9
    },
    {
     "x": 1300,
     "y": 700,
     "r": 110,
     "n": 10
    }
   ]
  },
  "moon": {
   "dx": 0.2,
   "dy": 1,
   "rgb": "255,120,60",
   "w": 0.65,
   "fill": "120,60,50"
  },
  "teamA": "#f2ece0",
  "teamB": "#20c8ff",
  "fire": "255,140,50",
  "laser": "40,200,255",
  "muzzle": "255,200,110",
  "gate": "255,190,120",
  "crystal": "255,90,40",
  "gateAccent": "#ffb070",
  "gateInner": "rgba(30,14,10,0.9)",
  "halo": "200,90,60",
  "smoke": {
   "rgb": "60,40,36",
   "a": 0.2,
   "size": 6
  },
  "plume": 1313802,
  "bloom": [
   0.65,
   0.5,
   0.68
  ],
  "grade": {
   "vignette": 0.6,
   "sat": 1.05
  },
  "exposure": 1.1,
  "extra2d": "embers"
 },
 "actors": [
  {
   "kind": "smoke",
   "x": 718,
   "y": 379,
   "opts": {
    "pts": [
     [
      718,
      379
     ],
     [
      727.0909090909091,
      373.60743801652893
     ],
     [
      736.1818181818181,
      368.3388429752066
     ],
     [
      745.2727272727273,
      363.1942148760331
     ],
     [
      754.3636363636364,
      358.1735537190083
     ],
     [
      763.4545454545455,
      353.27685950413223
     ],
     [
      772.5454545454545,
      348.5041322314049
     ],
     [
      781.6363636363636,
      343.8553719008264
     ],
     [
      790.7272727272727,
      339.3305785123967
     ],
     [
      799.8181818181819,
      334.92975206611567
     ],
     [
      808.9090909090909,
      330.65289256198344
     ],
     [
      818,
      326.5
     ],
     [
      827.0909090909091,
      322.4710743801653
     ],
     [
      836.1818181818182,
      318.56611570247935
     ],
     [
      845.2727272727273,
      314.78512396694214
     ],
     [
      854.3636363636364,
      311.1280991735537
     ],
     [
      863.4545454545455,
      307.59504132231405
     ],
     [
      872.5454545454545,
      304.1859504132231
     ],
     [
      881.6363636363636,
      300.900826446281
     ],
     [
      890.7272727272727,
      297.73966942148763
     ],
     [
      899.8181818181818,
      294.7024793388429
     ],
     [
      908.9090909090909,
      291.7892561983471
     ]
    ],
    "rgb": "60,40,36",
    "a": 0.2,
    "size": 6
   },
   "lit": null
  },
  {
   "kind": "turret",
   "x": 548,
   "y": 363,
   "opts": {
    "face": -1,
    "aim": 0.22,
    "muzzle": true
   },
   "lit": {
    "size": 1.2,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "stick",
   "x": 385,
   "y": 300,
   "opts": {
    "aim": -0.33,
    "weapon": "laser",
    "accent": "#20c8ff",
    "jet": true,
    "pose": "jet"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "stick",
   "x": 700,
   "y": 417,
   "opts": {
    "aim": 0.5,
    "weapon": "bazooka",
    "accent": "#f2ece0",
    "marker": "#f2ece0"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "stick",
   "x": 1215,
   "y": 498,
   "opts": {
    "face": -1,
    "aim": -0.1,
    "weapon": "flamer",
    "accent": "#f2ece0",
    "flame": [
     {
      "x": 15,
      "y": 0.5,
      "r": 3,
      "rgb": "255,215,110",
      "a": 0.9
     },
     {
      "x": 19.5,
      "y": 1.5,
      "r": 4.8,
      "rgb": "255,215,110",
      "a": 0.8200000000000001
     },
     {
      "x": 24,
      "y": 0.5,
      "r": 6.6,
      "rgb": "255,215,110",
      "a": 0.74
     },
     {
      "x": 28.5,
      "y": 1.5,
      "r": 8.4,
      "rgb": "255,110,30",
      "a": 0.66
     },
     {
      "x": 33,
      "y": 0.5,
      "r": 10.2,
      "rgb": "255,110,30",
      "a": 0.5800000000000001
     },
     {
      "x": 37.5,
      "y": 1.5,
      "r": 12,
      "rgb": "255,110,30",
      "a": 0.5
     },
     {
      "x": 42,
      "y": 0.5,
      "r": 13.8,
      "rgb": "255,110,30",
      "a": 0.42000000000000004
     }
    ]
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "rocket",
   "x": 918,
   "y": 289,
   "opts": {
    "ang": 0.3039197968541132
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "gate",
   "x": 110,
   "y": 334,
   "opts": {
    "s": 1.35,
    "accent": "#ffb070",
    "inner": "rgba(30,14,10,0.9)"
   },
   "lit": {
    "size": 1.4,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "crystals",
   "x": 250,
   "y": 350,
   "opts": {
    "glowRGB": "255,90,40"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "crystals",
   "x": 1110,
   "y": 229,
   "opts": {
    "glowRGB": "255,90,40",
    "n": 4,
    "seed": 11,
    "s": 0.8
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "beetle",
   "x": 990,
   "y": 484.5,
   "opts": {
    "rot": 0.45
   },
   "lit": {
    "size": 0.6,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "spider",
   "x": 735,
   "y": 551.5,
   "opts": {
    "face": -1,
    "eye": "#ff4020"
   },
   "lit": {
    "size": 0.6,
    "halo": "200,90,60",
    "shadow": true
   }
  },
  {
   "kind": "bird",
   "x": 610,
   "y": 120,
   "opts": {
    "flap": 0.2,
    "s": 1
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "bird",
   "x": 640,
   "y": 104,
   "opts": {
    "flap": 0.8,
    "s": 0.85
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "bird",
   "x": 668,
   "y": 128,
   "opts": {
    "flap": 0.5,
    "s": 0.9
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "bird",
   "x": 890,
   "y": 70,
   "opts": {
    "flap": 0.1,
    "s": 0.7
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  }
 ],
 "fx": [
  {
   "kind": "ribbon",
   "pts": [
    [
     499.97,
     328.98
    ],
    [
     509.56,
     333.04
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     471.2,
     316.8
    ],
    [
     480.79,
     320.86
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     442.43,
     304.62
    ],
    [
     452.02,
     308.68
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     413.65999999999997,
     292.44
    ],
    [
     423.25,
     296.5
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 526,
   "y": 340,
   "z": 42,
   "size": 34,
   "color": [
    2.5,
    1.6,
    0.6
   ],
   "alpha": 0.9,
   "additive": true
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     403,
     270
    ],
    [
     550,
     343
    ]
   ],
   "width": 6,
   "core": [
    1.2,
    3.4,
    3.6
   ],
   "glow": [
    0.05,
    0.5,
    0.7
   ],
   "z": 41,
   "fadePow": 0.2,
   "headBoost": 0
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 550,
   "y": 343,
   "z": 43,
   "size": 46,
   "color": [
    0.4,
    1.6,
    2
   ],
   "alpha": 1,
   "additive": true
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 382,
   "y": 294,
   "z": 43,
   "size": 16,
   "color": [
    2.2,
    1,
    0.3
   ],
   "alpha": 0.7,
   "additive": true
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 910,
   "y": 289,
   "z": 43,
   "size": 16,
   "color": [
    2.4,
    1.2,
    0.3
   ],
   "alpha": 0.9,
   "additive": true
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 1179,
   "y": 472,
   "z": 43,
   "size": 60,
   "color": [
    1.6,
    0.6,
    0.15
   ],
   "alpha": 0.7,
   "additive": true
  },
  {
   "kind": "explosion",
   "x": 1115,
   "y": 522,
   "scale": 0.5,
   "smoke": 1313802,
   "z": 50
  }
 ],
 "hud": {
  "timer": "1:34",
  "accent": "#f2ece0",
  "dark": true,
  "bottomLight": true,
  "timerLight": true
 },
 "labels": []
}
