// Generated by dump-mockup.mjs from tasks/M23/reference/mockup-src — do not edit; re-run it.
import type { SceneData } from '../scene'
import { space } from './space.mask'

export const F3: SceneData = {
 "id": "F3",
 "title": "space",
 "theme": "asteroid",
 "camera": {
  "x": 0,
  "y": 0,
  "w": 1280,
  "h": 720
 },
 "mask": space,
 "look": {
  "fogBack": {
   "color": [
    0.1,
    0.07,
    0.16
   ],
   "y0": 420,
   "y1": 640,
   "k": 0.6,
   "scale": 0.003
  },
  "fogFront": null,
  "fg": null,
  "lights": [
   {
    "x": 900,
    "y": 205,
    "z": 70,
    "r": 420,
    "rgb": "255,140,50",
    "i": 3
   },
   {
    "x": 480,
    "y": 327,
    "z": 20,
    "r": 170,
    "rgb": "40,225,210",
    "i": 2.4
   },
   {
    "x": 1038,
    "y": 141,
    "z": 30,
    "r": 120,
    "rgb": "255,200,110",
    "i": 1.8
   },
   {
    "x": 704,
    "y": 326,
    "z": 20,
    "r": 100,
    "rgb": "255,140,50",
    "i": 1.3
   },
   {
    "x": 740,
    "y": 161,
    "z": 20,
    "r": 120,
    "rgb": "255,140,50",
    "i": 1.5
   },
   {
    "x": 1100,
    "y": 477,
    "z": 30,
    "r": 150,
    "rgb": "255,120,220",
    "i": 1.6
   },
   {
    "x": 250,
    "y": 267,
    "z": 20,
    "r": 120,
    "rgb": "90,255,220",
    "i": 1.3
   },
   {
    "x": 650,
    "y": 110,
    "z": 20,
    "r": 90,
    "rgb": "255,190,80",
    "i": 1
   },
   {
    "x": 1180,
    "y": 350,
    "z": 20,
    "r": 110,
    "rgb": "255,140,50",
    "i": 1.3
   }
  ],
  "bloom": [
   0.6,
   0.45,
   0.7
  ],
  "grade": {
   "vignette": 0.6,
   "sat": 1.05,
   "cool": [
    0.88,
    0.95,
    1.15
   ]
  },
  "exposure": 1.1,
  "bg": {
   "skyTop": 197640,
   "skyBottom": 1972272,
   "haze": 2892864,
   "horizon": 620,
   "stars": 0.006,
   "grainK": 0.02,
   "rays": [
    150,
    60,
    0.12,
    700
   ],
   "rayColor": 13160703,
   "sun": {
    "x": 150,
    "y": 60,
    "r": 8,
    "k": 1,
    "color": 16777215
   },
   "glowY": 620,
   "glowColor": 2102838,
   "layers": [
    {
     "shape": "arc",
     "x": 980,
     "y": 130,
     "r": 620,
     "color": 2038572,
     "step": 6,
     "soft": 3,
     "fade": [
      360,
      620,
      0.5
     ],
     "jitter": 0.8
    },
    {
     "shape": "arc",
     "x": 240,
     "y": 330,
     "r": 260,
     "color": 1446687,
     "step": 5,
     "soft": 1.8,
     "fade": [
      440,
      620,
      0.5
     ],
     "jitter": 0.6
    },
    {
     "shape": "arc",
     "x": 720,
     "y": 560,
     "r": 1100,
     "color": 920596,
     "step": 5,
     "soft": 1.2,
     "fade": [
      620,
      720,
      0.6
     ],
     "jitter": 0.5
    }
   ]
  },
  "terrain": {
   "scorch": [
    {
     "x": 900,
     "y": 205,
     "r": 80
    }
   ],
   "sunDir": [
    -0.7,
    0.55,
    0.42
   ],
   "sunCol": [
    0.75,
    0.78,
    0.9
   ],
   "sky": [
    0.03,
    0.03,
    0.06
   ],
   "ground": [
    0.02,
    0.015,
    0.03
   ],
   "rimCol": [
    0.45,
    0.55,
    1
   ],
   "rimK": 0.5,
   "lipK": 0.1,
   "lipCol": [
    0.6,
    0.65,
    0.9
   ],
   "interior": 0.65,
   "bevel": 14
  },
  "moon": {
   "dx": -0.75,
   "dy": -0.65,
   "rgb": "215,225,255",
   "w": 0.8,
   "fill": "70,60,110"
  }
 },
 "palette": null,
 "actors": [
  {
   "kind": "smoke",
   "x": 448,
   "y": 271,
   "opts": {
    "pts": [
     [
      448,
      271
     ],
     [
      461.6363636363636,
      266
     ],
     [
      475.27272727272725,
      261
     ],
     [
      488.9090909090909,
      256
     ],
     [
      502.54545454545456,
      251
     ],
     [
      516.1818181818181,
      246
     ],
     [
      529.8181818181818,
      241
     ],
     [
      543.4545454545455,
      236
     ],
     [
      557.0909090909091,
      231
     ],
     [
      570.7272727272727,
      226
     ],
     [
      584.3636363636364,
      221
     ],
     [
      598,
      216
     ],
     [
      611.6363636363636,
      211
     ],
     [
      625.2727272727273,
      206
     ],
     [
      638.9090909090909,
      201
     ],
     [
      652.5454545454545,
      196
     ],
     [
      666.1818181818182,
      191
     ],
     [
      679.8181818181818,
      186
     ],
     [
      693.4545454545455,
      181
     ],
     [
      707.0909090909091,
      176
     ],
     [
      720.7272727272727,
      171
     ],
     [
      734.3636363636364,
      166
     ]
    ],
    "rgb": "120,110,140",
    "a": 0.12,
    "size": 5,
    "grow": 1.4
   },
   "lit": null
  },
  {
   "kind": "stick",
   "x": 700,
   "y": 330,
   "opts": {
    "face": -1,
    "rot": 0.3,
    "aim": -0.2,
    "weapon": "laser",
    "accent": "#18c2b8",
    "jet": true,
    "pose": "jet"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "stick",
   "x": 430,
   "y": 309,
   "opts": {
    "aim": 0.45,
    "weapon": "bazooka",
    "accent": "#e8482c",
    "marker": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "stick",
   "x": 1180,
   "y": 360,
   "opts": {
    "rot": -0.6,
    "aim": 0.2,
    "weapon": "flamer",
    "accent": "#e8482c",
    "jet": true,
    "pose": "jet",
    "face": -1
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "rocket",
   "x": 748,
   "y": 161,
   "opts": {
    "ang": 0.35144479400355166
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "turret",
   "x": 1060,
   "y": 165,
   "opts": {
    "face": -1,
    "aim": 0.3,
    "muzzle": true
   },
   "lit": {
    "size": 1.2,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "spider",
   "x": 960,
   "y": 345.5,
   "opts": {
    "rot": 3.141592653589793,
    "eye": "#ff5030"
   },
   "lit": {
    "size": 0.6,
    "halo": "110,120,190",
    "shadow": false
   }
  },
  {
   "kind": "beetle",
   "x": 1010,
   "y": 511.5,
   "opts": {
    "rot": 0.55
   },
   "lit": {
    "size": 0.6,
    "halo": "110,120,190",
    "shadow": true
   }
  },
  {
   "kind": "gate",
   "x": 1100,
   "y": 502,
   "opts": {
    "s": 1.3,
    "accent": "#ff9adf",
    "inner": "rgba(40,20,50,0.9)"
   },
   "lit": {
    "size": 1.4,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "crystals",
   "x": 250,
   "y": 283,
   "opts": {
    "glowRGB": "90,255,220"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "crystals",
   "x": 650,
   "y": 122,
   "opts": {
    "glowRGB": "255,190,80",
    "n": 4,
    "s": 0.7,
    "seed": 9
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": false
   }
  }
 ],
 "fx": [
  {
   "kind": "ribbon",
   "pts": [
    [
     975.3,
     173.49
    ],
    [
     998.4,
     161.52
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     909.3,
     207.69
    ],
    [
     932.4,
     195.72
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     843.3,
     241.89000000000001
    ],
    [
     866.4,
     229.92000000000002
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     777.3,
     276.09000000000003
    ],
    [
     800.4,
     264.12
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 1038,
   "y": 141,
   "z": 42,
   "size": 34,
   "color": [
    2.5,
    1.6,
    0.6
   ],
   "alpha": 0.9,
   "additive": true
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     683,
     308
    ],
    [
     480,
     331
    ]
   ],
   "width": 6,
   "core": [
    1.2,
    3.4,
    3.6
   ],
   "glow": [
    0.05,
    0.5,
    0.7
   ],
   "z": 41,
   "fadePow": 0.2,
   "headBoost": 0
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 480,
   "y": 331,
   "z": 43,
   "size": 50,
   "color": [
    0.4,
    1.6,
    2
   ],
   "alpha": 1,
   "additive": true
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 740,
   "y": 161,
   "z": 43,
   "size": 16,
   "color": [
    2.4,
    1.2,
    0.3
   ],
   "alpha": 0.9,
   "additive": true
  },
  {
   "kind": "explosion",
   "x": 900,
   "y": 205,
   "scale": 0.5,
   "smoke": 1315356,
   "z": 50
  }
 ],
 "hud": {
  "timer": "1:12",
  "accent": "#e8482c",
  "dark": true,
  "bottomLight": true,
  "timerLight": true
 },
 "labels": []
}
