// Generated by dump-mockup.mjs from tasks/M23/reference/mockup-src — do not edit; re-run it.
import type { SceneData } from '../scene'
import { cast } from './cast.mask'

export const F4: SceneData = {
 "id": "F4",
 "title": "cast sheet",
 "theme": "dusk",
 "camera": {
  "x": 0,
  "y": 0,
  "w": 1280,
  "h": 720
 },
 "mask": cast,
 "look": {
  "fogBack": {
   "color": [
    0.16,
    0.13,
    0.17
   ],
   "y0": 420,
   "y1": 600,
   "k": 0.6
  },
  "fogFront": null,
  "fg": null,
  "lights": [
   {
    "x": 70,
    "y": 536,
    "z": 30,
    "r": 160,
    "rgb": "255,170,80",
    "i": 1.6
   },
   {
    "x": 380,
    "y": 543,
    "z": 30,
    "r": 170,
    "rgb": "40,225,210",
    "i": 2.4
   },
   {
    "x": 580,
    "y": 544,
    "z": 30,
    "r": 240,
    "rgb": "255,140,50",
    "i": 2.6
   },
   {
    "x": 678,
    "y": 480,
    "z": 20,
    "r": 170,
    "rgb": "255,140,50",
    "i": 2
   },
   {
    "x": 840,
    "y": 560,
    "z": 30,
    "r": 170,
    "rgb": "255,200,110",
    "i": 2
   },
   {
    "x": 1110,
    "y": 540,
    "z": 30,
    "r": 190,
    "rgb": "240,190,90",
    "i": 1.8
   },
   {
    "x": 1090,
    "y": 230,
    "z": 60,
    "r": 320,
    "rgb": "255,140,50",
    "i": 2.4
   },
   {
    "x": 630,
    "y": 230,
    "z": 20,
    "r": 140,
    "rgb": "110,170,255",
    "i": 1.6
   },
   {
    "x": 880,
    "y": 190,
    "z": 20,
    "r": 120,
    "rgb": "255,140,50",
    "i": 1.4
   }
  ],
  "bloom": [
   0.55,
   0.45,
   0.72
  ],
  "grade": {
   "vignette": 0.55
  },
  "exposure": 1.15,
  "bg": {
   "skyTop": 460815,
   "skyBottom": 3024438,
   "haze": 4076612,
   "horizon": 600,
   "stars": 0.003,
   "grainK": 0.02,
   "glowY": 600,
   "glowColor": 1708566,
   "layers": [
    {
     "shape": "pyramid",
     "x": 1040,
     "y": 150,
     "slope": 1.05,
     "color": 2893620,
     "step": 6,
     "soft": 2.5,
     "fade": [
      300,
      600,
      0.5
     ],
     "jitter": 1.2
    },
    {
     "shape": "pyramid",
     "x": 980,
     "y": 200,
     "slope": 1.05,
     "color": 2038567,
     "step": 6,
     "soft": 1.6,
     "fade": [
      340,
      600,
      0.55
     ],
     "jitter": 1
    }
   ]
  },
  "terrain": {
   "sunDir": [
    0.55,
    0.62,
    0.4
   ],
   "sunCol": [
    0.22,
    0.26,
    0.4
   ],
   "sky": [
    0.05,
    0.06,
    0.1
   ],
   "ground": [
    0.03,
    0.02,
    0.02
   ],
   "rimCol": [
    0.55,
    0.62,
    0.95
   ],
   "rimK": 0.5,
   "lipK": 0.14,
   "lipCol": [
    0.5,
    0.55,
    0.8
   ],
   "interior": 0.6,
   "bevel": 14
  },
  "moon": {
   "dx": 0.6,
   "dy": -0.8,
   "rgb": "185,195,245",
   "w": 0.75,
   "fill": "90,80,110"
  }
 },
 "palette": null,
 "actors": [
  {
   "kind": "stick",
   "x": 110,
   "y": 606,
   "opts": {
    "aim": 0.35,
    "weapon": "bazooka",
    "accent": "#e8482c",
    "marker": "#e8482c",
    "s": 3.4499999999999997
   },
   "lit": {
    "size": 3,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "stick",
   "x": 290,
   "y": 613,
   "opts": {
    "aim": 0.05,
    "weapon": "laser",
    "accent": "#18c2b8",
    "s": 3.4499999999999997
   },
   "lit": {
    "size": 3,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "stick",
   "x": 470,
   "y": 604,
   "opts": {
    "aim": -0.05,
    "weapon": "flamer",
    "accent": "#e8482c",
    "flame": [
     {
      "x": 15,
      "y": 0.5,
      "r": 2.5,
      "rgb": "255,215,100",
      "a": 0.85
     },
     {
      "x": 19.2,
      "y": 1.1,
      "r": 3.9,
      "rgb": "255,215,100",
      "a": 0.77
     },
     {
      "x": 23.4,
      "y": 0.5,
      "r": 5.3,
      "rgb": "255,215,100",
      "a": 0.69
     },
     {
      "x": 27.6,
      "y": 1.1,
      "r": 6.699999999999999,
      "rgb": "255,110,30",
      "a": 0.61
     },
     {
      "x": 31.8,
      "y": 0.5,
      "r": 8.1,
      "rgb": "255,110,30",
      "a": 0.53
     },
     {
      "x": 36,
      "y": 1.1,
      "r": 9.5,
      "rgb": "255,110,30",
      "a": 0.44999999999999996
     },
     {
      "x": 40.2,
      "y": 0.5,
      "r": 10.899999999999999,
      "rgb": "255,110,30",
      "a": 0.37
     },
     {
      "x": 44.400000000000006,
      "y": 1.1,
      "r": 12.299999999999999,
      "rgb": "255,110,30",
      "a": 0.2899999999999999
     }
    ],
    "s": 3.4499999999999997
   },
   "lit": {
    "size": 3,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "stick",
   "x": 690,
   "y": 520,
   "opts": {
    "aim": 0.25,
    "weapon": "laser",
    "accent": "#18c2b8",
    "jet": true,
    "pose": "jet",
    "s": 3.4499999999999997
   },
   "lit": {
    "size": 3,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "turret",
   "x": 900,
   "y": 615,
   "opts": {
    "s": 3,
    "face": -1,
    "aim": 0.25,
    "muzzle": true
   },
   "lit": {
    "size": 3,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "gate",
   "x": 1110,
   "y": 595,
   "opts": {
    "s": 2.8499999999999996,
    "accent": "#f0c060",
    "inner": "rgba(40,30,44,0.9)"
   },
   "lit": {
    "size": 3,
    "halo": null,
    "shadow": true
   }
  },
  {
   "kind": "beetle",
   "x": 110,
   "y": 250,
   "opts": {
    "s": 3
   },
   "lit": {
    "size": 2,
    "halo": "120,120,170",
    "shadow": false
   }
  },
  {
   "kind": "spider",
   "x": 270,
   "y": 250,
   "opts": {
    "s": 3
   },
   "lit": {
    "size": 2,
    "halo": "120,120,170",
    "shadow": false
   }
  },
  {
   "kind": "bird",
   "x": 420,
   "y": 210,
   "opts": {
    "s": 3,
    "flap": 0.15
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "bird",
   "x": 500,
   "y": 225,
   "opts": {
    "s": 2.4000000000000004,
    "flap": 0.85
   },
   "lit": {
    "size": 1.2,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "crystals",
   "x": 630,
   "y": 250,
   "opts": {
    "s": 2.4000000000000004
   },
   "lit": {
    "size": 2,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "smoke",
   "x": 740,
   "y": 220,
   "opts": {
    "pts": [
     [
      740,
      220
     ],
     [
      750,
      218
     ],
     [
      760,
      216
     ],
     [
      770,
      214
     ],
     [
      780,
      212
     ],
     [
      790,
      210
     ],
     [
      800,
      208
     ],
     [
      810,
      206
     ],
     [
      820,
      204
     ],
     [
      830,
      202
     ],
     [
      840,
      200
     ],
     [
      850,
      198
     ],
     [
      860,
      196
     ],
     [
      870,
      194
     ]
    ],
    "rgb": "130,120,130",
    "a": 0.16,
    "size": 9,
    "grow": 1.5
   },
   "lit": null
  },
  {
   "kind": "rocket",
   "x": 890,
   "y": 192,
   "opts": {
    "ang": 0.2,
    "s": 2.4
   },
   "lit": {
    "size": 2,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "stick",
   "x": 1030,
   "y": 440,
   "opts": {
    "s": 1.8,
    "aim": 0.95,
    "weapon": "bazooka",
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.8,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "stick",
   "x": 1120,
   "y": 440,
   "opts": {
    "s": 1.8,
    "aim": 0.3,
    "weapon": "bazooka",
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.8,
    "halo": null,
    "shadow": false
   }
  },
  {
   "kind": "stick",
   "x": 1210,
   "y": 440,
   "opts": {
    "s": 1.8,
    "aim": -0.45,
    "weapon": "bazooka",
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.8,
    "halo": null,
    "shadow": false
   }
  }
 ],
 "fx": [
  {
   "kind": "ribbon",
   "pts": [
    [
     343.475,
     538.825
    ],
    [
     410,
     535.825
    ]
   ],
   "width": 6,
   "core": [
    1.2,
    3.4,
    3.6
   ],
   "glow": [
    0.05,
    0.5,
    0.7
   ],
   "z": 41,
   "fadePow": 0.2,
   "headBoost": 0
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 840,
   "y": 563,
   "z": 42,
   "size": 40,
   "color": [
    2.5,
    1.6,
    0.6
   ],
   "alpha": 0.9,
   "additive": true
  },
  {
   "kind": "ribbon",
   "pts": [
    [
     750,
     553
    ],
    [
     800,
     557
    ]
   ],
   "width": 3,
   "core": [
    4,
    3,
    1.4
   ],
   "glow": [
    1,
    0.45,
    0.08
   ],
   "z": 40,
   "fadePow": 1.2,
   "headBoost": 1
  },
  {
   "kind": "sprite",
   "tex": "soft",
   "x": 870,
   "y": 195,
   "z": 43,
   "size": 26,
   "color": [
    2.4,
    1.2,
    0.3
   ],
   "alpha": 0.9,
   "additive": true
  },
  {
   "kind": "explosion",
   "x": 1090,
   "y": 225,
   "scale": 0.45,
   "smoke": 1709080,
   "z": 50
  }
 ],
 "hud": null,
 "labels": [
  {
   "text": "B A Z O O K A   ·   Y O U",
   "x": 110,
   "y": 660,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "L A S E R   ·   E N E M Y",
   "x": 290,
   "y": 660,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "F L A M E T H R O W E R",
   "x": 470,
   "y": 660,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "J E T P A C K",
   "x": 690,
   "y": 660,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "G U N   P L A T F O R M",
   "x": 900,
   "y": 660,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "G A T E",
   "x": 1110,
   "y": 660,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "B E E T L E",
   "x": 110,
   "y": 280,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "S P I D E R",
   "x": 270,
   "y": 280,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "B I R D S",
   "x": 460,
   "y": 280,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "C R Y S T A L S",
   "x": 630,
   "y": 280,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "R O C K E T",
   "x": 830,
   "y": 280,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "E X P L O S I O N",
   "x": 1090,
   "y": 280,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "A I M   R E A D S   A T   A   G L A N C E",
   "x": 1120,
   "y": 462,
   "font": "12px Georgia, serif",
   "fill": "rgba(225,218,230,0.7)",
   "align": "center"
  },
  {
   "text": "Cast at 3× — ink silhouettes, rim-lit by whatever is firing nearby; team colour only in the scarf and marker.",
   "x": 30,
   "y": 40,
   "font": "italic 15px Georgia, serif",
   "fill": "rgba(225,218,230,0.75)",
   "align": "left"
  }
 ]
}
