// Generated by dump-mockup.mjs from tasks/M23/reference/mockup-src — do not edit; re-run it.
import type { SceneData } from '../scene'
import { arsenal } from './arsenal.mask'

export const F6: SceneData = {
 "id": "F6",
 "title": "weapon sheet",
 "theme": "dusk",
 "camera": {
  "x": 0,
  "y": 0,
  "w": 1280,
  "h": 720
 },
 "mask": arsenal,
 "look": {
  "fogBack": null,
  "fogFront": null,
  "fg": null,
  "lights": [
   {
    "x": 146.00166666666667,
    "y": 112.618,
    "z": 20,
    "r": 110,
    "rgb": "255,130,40",
    "i": 1.8
   },
   {
    "x": 310,
    "y": 102.30250000000001,
    "z": 20,
    "r": 110,
    "rgb": "255,130,40",
    "i": 1.8
   },
   {
    "x": 561.4558333333333,
    "y": 115.7575,
    "z": 20,
    "r": 110,
    "rgb": "255,176,32",
    "i": 1.8
   },
   {
    "x": 752.3641666666666,
    "y": 115.309,
    "z": 20,
    "r": 110,
    "rgb": "40,225,210",
    "i": 1.8
   },
   {
    "x": 997.0925,
    "y": 116.6545,
    "z": 20,
    "r": 110,
    "rgb": "40,225,210",
    "i": 1.8
   },
   {
    "x": 1174.5458333333333,
    "y": 114.412,
    "z": 20,
    "r": 110,
    "rgb": "255,176,32",
    "i": 1.8
   },
   {
    "x": 114.60666666666665,
    "y": 241.9635,
    "z": 20,
    "r": 110,
    "rgb": "255,176,32",
    "i": 1.8
   },
   {
    "x": 325.6975,
    "y": 241.515,
    "z": 20,
    "r": 110,
    "rgb": "255,176,32",
    "i": 1.8
   },
   {
    "x": 586.1233333333333,
    "y": 243.309,
    "z": 20,
    "r": 110,
    "rgb": "255,176,32",
    "i": 1.8
   },
   {
    "x": 754.6066666666666,
    "y": 247.794,
    "z": 20,
    "r": 110,
    "rgb": "200,210,240",
    "i": 0.6
   },
   {
    "x": 981.3950000000001,
    "y": 241.515,
    "z": 20,
    "r": 110,
    "rgb": "200,210,240",
    "i": 0.6
   },
   {
    "x": 1235.0933333333335,
    "y": 259.455,
    "z": 20,
    "r": 110,
    "rgb": "255,235,170",
    "i": 1.8
   },
   {
    "x": 128.06166666666667,
    "y": 365.03,
    "z": 20,
    "r": 110,
    "rgb": "200,210,240",
    "i": 0.6
   },
   {
    "x": 341.395,
    "y": 374,
    "z": 20,
    "r": 110,
    "rgb": "200,210,240",
    "i": 0.6
   },
   {
    "x": 565.9408333333333,
    "y": 376.2425,
    "z": 20,
    "r": 110,
    "rgb": "255,130,40",
    "i": 1.8
   },
   {
    "x": 735.3211666666666,
    "y": 362.7875,
    "z": 20,
    "r": 110,
    "rgb": "255,50,40",
    "i": 1.8
   },
   {
    "x": 948.6545,
    "y": 356.06,
    "z": 20,
    "r": 110,
    "rgb": "255,130,40",
    "i": 1.8
   },
   {
    "x": 1163.3333333333335,
    "y": 358.3025,
    "z": 20,
    "r": 110,
    "rgb": "150,145,160",
    "i": 1.8
   },
   {
    "x": 99.80616666666667,
    "y": 461.635,
    "z": 20,
    "r": 110,
    "rgb": "255,130,40",
    "i": 1.8
   },
   {
    "x": 310,
    "y": 486.3025,
    "z": 20,
    "r": 110,
    "rgb": "125,255,70",
    "i": 1.8
   },
   {
    "x": 568.1833333333334,
    "y": 502,
    "z": 20,
    "r": 110,
    "rgb": "200,210,240",
    "i": 0.6
   },
   {
    "x": 686.6666666666666,
    "y": 480,
    "z": 20,
    "r": 120,
    "rgb": "255,176,32",
    "i": 1.8
   }
  ],
  "bloom": [
   0.5,
   0.4,
   0.75
  ],
  "grade": {
   "vignette": 0.5
  },
  "exposure": 1.15,
  "bg": {
   "skyTop": 460815,
   "skyBottom": 2761778,
   "haze": 3813954,
   "horizon": 690,
   "stars": 0.003,
   "grainK": 0.02,
   "glowY": 690,
   "glowColor": 1708566,
   "layers": [
    {
     "shape": "pyramid",
     "x": 1080,
     "y": 360,
     "slope": 1.05,
     "color": 2235946,
     "step": 6,
     "soft": 2,
     "fade": [
      450,
      690,
      0.5
     ],
     "jitter": 1.1
    }
   ]
  },
  "terrain": {
   "sunDir": [
    0.55,
    0.62,
    0.4
   ],
   "sunCol": [
    0.22,
    0.26,
    0.4
   ],
   "sky": [
    0.05,
    0.06,
    0.1
   ],
   "ground": [
    0.03,
    0.02,
    0.02
   ],
   "rimCol": [
    0.55,
    0.62,
    0.95
   ],
   "rimK": 0.5,
   "lipK": 0.14,
   "lipCol": [
    0.5,
    0.55,
    0.8
   ],
   "interior": 0.6,
   "bevel": 12
  },
  "moon": {
   "dx": 0.6,
   "dy": -0.8,
   "rgb": "185,195,245",
   "w": 0.75,
   "fill": "90,80,110"
  }
 },
 "palette": null,
 "actors": [
  {
   "kind": "weapon",
   "x": 86.66666666666667,
   "y": 118,
   "opts": {
    "key": "bazooka",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -13.454999999999998,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    27,
    95,
    138,
    129
   ]
  },
  {
   "kind": "weapon",
   "x": 300,
   "y": 118,
   "opts": {
    "key": "grenade",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -42.607500000000016,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    289,
    85,
    317,
    116
   ]
  },
  {
   "kind": "weapon",
   "x": 513.3333333333334,
   "y": 118,
   "opts": {
    "key": "smg",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -22.42500000000001,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    474,
    109,
    557,
    145
   ]
  },
  {
   "kind": "weapon",
   "x": 726.6666666666666,
   "y": 118,
   "opts": {
    "key": "laser_pistol",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -49.335000000000036,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    713,
    109,
    745,
    135
   ]
  },
  {
   "kind": "weapon",
   "x": 940,
   "y": 118,
   "opts": {
    "key": "laser_smg",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -22.424999999999955,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    903,
    107,
    989,
    140
   ]
  },
  {
   "kind": "weapon",
   "x": 1153.3333333333335,
   "y": 118,
   "opts": {
    "key": "pistol",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -49.335000000000036,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    1140,
    109,
    1168,
    135
   ]
  },
  {
   "kind": "weapon",
   "x": 86.66666666666667,
   "y": 246,
   "opts": {
    "key": "revolver",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -51.57749999999999,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    68,
    236,
    107,
    264
   ]
  },
  {
   "kind": "weapon",
   "x": 300,
   "y": 246,
   "opts": {
    "key": "deagle",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -51.577499999999986,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    282,
    233,
    319,
    266
   ]
  },
  {
   "kind": "weapon",
   "x": 513.3333333333334,
   "y": 246,
   "opts": {
    "key": "machinegun",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -22.42500000000001,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    463,
    226,
    581,
    269
   ]
  },
  {
   "kind": "weapon",
   "x": 726.6666666666666,
   "y": 246,
   "opts": {
    "key": "knife",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -51.577499999999986,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    708,
    242,
    747,
    256
   ]
  },
  {
   "kind": "weapon",
   "x": 940,
   "y": 246,
   "opts": {
    "key": "bat",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -53.819999999999936,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    912,
    236,
    978,
    254
   ]
  },
  {
   "kind": "weapon",
   "x": 1153.3333333333335,
   "y": 246,
   "opts": {
    "key": "whip",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -89.70000000000005,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    1094,
    230,
    1230,
    263
   ]
  },
  {
   "kind": "weapon",
   "x": 86.66666666666667,
   "y": 374,
   "opts": {
    "key": "axe",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -53.81999999999999,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    56,
    345,
    127,
    395
   ]
  },
  {
   "kind": "weapon",
   "x": 300,
   "y": 374,
   "opts": {
    "key": "hammer",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -53.81999999999999,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    269,
    355,
    340,
    397
   ]
  },
  {
   "kind": "weapon",
   "x": 513.3333333333334,
   "y": 374,
   "opts": {
    "key": "flamethrower",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -17.939999999999998,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    474,
    366,
    567,
    406
   ]
  },
  {
   "kind": "weapon",
   "x": 726.6666666666666,
   "y": 374,
   "opts": {
    "key": "mine",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -43.952999999999975,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    711,
    345,
    744,
    374
   ]
  },
  {
   "kind": "weapon",
   "x": 940,
   "y": 374,
   "opts": {
    "key": "airburst",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -43.952999999999975,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    925,
    337,
    958,
    378
   ]
  },
  {
   "kind": "weapon",
   "x": 1153.3333333333335,
   "y": 374,
   "opts": {
    "key": "smoke",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -42.60750000000007,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    1145,
    337,
    1165,
    373
   ]
  },
  {
   "kind": "weapon",
   "x": 86.66666666666667,
   "y": 502,
   "opts": {
    "key": "molotov",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -43.952999999999996,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    69,
    439,
    109,
    502
   ]
  },
  {
   "kind": "weapon",
   "x": 300,
   "y": 502,
   "opts": {
    "key": "toxic_grenade",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -42.607500000000016,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    292,
    468,
    311,
    502
   ]
  },
  {
   "kind": "weapon",
   "x": 513.3333333333334,
   "y": 502,
   "opts": {
    "key": "shovel",
    "s": 4.484999999999999,
    "accent": "#e8482c",
    "origin": [
     -44.85000000000002,
     0
    ]
   },
   "lit": {
    "size": 1.5,
    "halo": null,
    "shadow": false
   },
   "box": [
    467,
    489,
    565,
    518
   ]
  },
  {
   "kind": "turret",
   "x": 726.6666666666666,
   "y": 528,
   "opts": {
    "s": 2.4,
    "face": -1,
    "aim": 0.18,
    "muzzle": true
   },
   "lit": {
    "size": 2.4,
    "halo": null,
    "shadow": true
   },
   "box": [
    658,
    455,
    770,
    535
   ]
  },
  {
   "kind": "stick",
   "x": 42.666666666666664,
   "y": 690,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "bazooka",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    29,
    652,
    62,
    693
   ]
  },
  {
   "kind": "stick",
   "x": 99.55555555555554,
   "y": 689,
   "opts": {
    "aim": 0.9,
    "accent": "#18c2b8",
    "held": "grenade",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    86,
    647,
    111,
    692
   ]
  },
  {
   "kind": "stick",
   "x": 156.44444444444443,
   "y": 689,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "smg",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    143,
    651,
    175,
    692
   ]
  },
  {
   "kind": "stick",
   "x": 213.33333333333331,
   "y": 701,
   "opts": {
    "aim": 0.12,
    "accent": "#18c2b8",
    "held": "laser_pistol",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    200,
    663,
    232,
    704
   ]
  },
  {
   "kind": "stick",
   "x": 270.22222222222223,
   "y": 699,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "laser_smg",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    257,
    661,
    290,
    702
   ]
  },
  {
   "kind": "stick",
   "x": 327.1111111111111,
   "y": 684,
   "opts": {
    "aim": 0.12,
    "accent": "#18c2b8",
    "held": "pistol",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    314,
    646,
    345,
    687
   ]
  },
  {
   "kind": "stick",
   "x": 384,
   "y": 685,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "revolver",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    371,
    647,
    405,
    688
   ]
  },
  {
   "kind": "stick",
   "x": 440.88888888888886,
   "y": 693,
   "opts": {
    "aim": 0.12,
    "accent": "#18c2b8",
    "held": "deagle",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    428,
    655,
    461,
    696
   ]
  },
  {
   "kind": "stick",
   "x": 497.77777777777777,
   "y": 686,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "machinegun",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    484,
    648,
    523,
    689
   ]
  },
  {
   "kind": "stick",
   "x": 554.6666666666666,
   "y": 697,
   "opts": {
    "aim": 0.12,
    "accent": "#18c2b8",
    "held": "knife",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    541,
    659,
    575,
    700
   ]
  },
  {
   "kind": "stick",
   "x": 611.5555555555555,
   "y": 693,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "bat",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    598,
    655,
    637,
    696
   ]
  },
  {
   "kind": "stick",
   "x": 668.4444444444445,
   "y": 688,
   "opts": {
    "aim": 0.12,
    "accent": "#18c2b8",
    "held": "whip",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    655,
    650,
    713,
    691
   ]
  },
  {
   "kind": "stick",
   "x": 725.3333333333333,
   "y": 684,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "axe",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    712,
    646,
    752,
    687
   ]
  },
  {
   "kind": "stick",
   "x": 782.2222222222222,
   "y": 688,
   "opts": {
    "aim": 0.12,
    "accent": "#18c2b8",
    "held": "hammer",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    769,
    650,
    809,
    691
   ]
  },
  {
   "kind": "stick",
   "x": 839.1111111111111,
   "y": 698,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "flamethrower",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    826,
    660,
    859,
    701
   ]
  },
  {
   "kind": "stick",
   "x": 896,
   "y": 703,
   "opts": {
    "aim": 0.9,
    "accent": "#18c2b8",
    "held": "mine",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    883,
    662,
    907,
    706
   ]
  },
  {
   "kind": "stick",
   "x": 952.8888888888888,
   "y": 693,
   "opts": {
    "aim": 0.9,
    "accent": "#e8482c",
    "held": "airburst",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    940,
    652,
    966,
    696
   ]
  },
  {
   "kind": "stick",
   "x": 1009.7777777777777,
   "y": 686,
   "opts": {
    "aim": 0.9,
    "accent": "#18c2b8",
    "held": "smoke",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    996,
    644,
    1021,
    689
   ]
  },
  {
   "kind": "stick",
   "x": 1066.6666666666665,
   "y": 685,
   "opts": {
    "aim": 0.9,
    "accent": "#e8482c",
    "held": "molotov",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    1053,
    639,
    1078,
    688
   ]
  },
  {
   "kind": "stick",
   "x": 1123.5555555555554,
   "y": 692,
   "opts": {
    "aim": 0.9,
    "accent": "#18c2b8",
    "held": "toxic_grenade",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    1110,
    651,
    1135,
    695
   ]
  },
  {
   "kind": "stick",
   "x": 1180.4444444444443,
   "y": 700,
   "opts": {
    "aim": 0.12,
    "accent": "#e8482c",
    "held": "shovel",
    "heldAccent": "#e8482c"
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    1167,
    662,
    1207,
    703
   ]
  },
  {
   "kind": "turret",
   "x": 1237.3333333333333,
   "y": 686,
   "opts": {
    "face": -1,
    "aim": 0.2,
    "muzzle": true
   },
   "lit": {
    "size": 1,
    "halo": null,
    "shadow": true
   },
   "box": [
    1209,
    655,
    1256,
    689
   ]
  }
 ],
 "fx": [],
 "hud": null,
 "labels": [
  {
   "text": "B A Z O O K A",
   "x": 106.66666666666667,
   "y": 166,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "G R E N A D E",
   "x": 320,
   "y": 166,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "S M G",
   "x": 533.3333333333334,
   "y": 166,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "L A S E R   P I S T O L",
   "x": 746.6666666666666,
   "y": 166,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "L A S E R   S M G",
   "x": 960,
   "y": 166,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "P I S T O L",
   "x": 1173.3333333333335,
   "y": 166,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R E V O L V E R",
   "x": 106.66666666666667,
   "y": 294,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "D E A G L E",
   "x": 320,
   "y": 294,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "M A C H I N E G U N",
   "x": 533.3333333333334,
   "y": 294,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "K N I F E",
   "x": 746.6666666666666,
   "y": 294,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "B A T",
   "x": 960,
   "y": 294,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "W H I P",
   "x": 1173.3333333333335,
   "y": 294,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "A X E",
   "x": 106.66666666666667,
   "y": 422,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "H A M M E R",
   "x": 320,
   "y": 422,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "F L A M E T H R O W E R",
   "x": 533.3333333333334,
   "y": 422,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "M I N E",
   "x": 746.6666666666666,
   "y": 422,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "A I R B U R S T",
   "x": 960,
   "y": 422,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "S M O K E",
   "x": 1173.3333333333335,
   "y": 422,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "M O L O T O V",
   "x": 106.66666666666667,
   "y": 550,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "T O X I C   G R E N A D E",
   "x": 320,
   "y": 550,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "S H O V E L",
   "x": 533.3333333333334,
   "y": 550,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "P L A T F O R M   G U N",
   "x": 746.6666666666666,
   "y": 550,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "meteor — skipped: a world event (meteor shower), never held.",
   "x": 900,
   "y": 505,
   "font": "italic 13px Georgia, serif",
   "fill": "rgba(225,218,230,0.5)",
   "align": "left"
  },
  {
   "text": "1× game scale",
   "x": 14,
   "y": 640,
   "font": "italic 12px Georgia, serif",
   "fill": "rgba(225,218,230,0.55)",
   "align": "left"
  },
  {
   "text": "M23 arsenal at ~4.5× — ink silhouettes, rim-lit by their own muzzle or effect; the bottom row is every weapon in hand at 1×.",
   "x": 24,
   "y": 34,
   "font": "italic 15px Georgia, serif",
   "fill": "rgba(225,218,230,0.78)",
   "align": "left"
  }
 ]
}
