// Generated by dump-mockup.mjs from tasks/M23/reference/mockup-src — do not edit; re-run it.
import type { SceneData } from '../scene'
import { poses } from './poses.mask'

export const F7: SceneData = {
 "id": "F7",
 "title": "pose sheet",
 "theme": "dusk",
 "camera": {
  "x": 0,
  "y": 0,
  "w": 1280,
  "h": 720
 },
 "mask": poses,
 "look": {
  "fogBack": null,
  "fogFront": null,
  "fg": null,
  "lights": [
   {
    "x": 280,
    "y": 385,
    "z": 20,
    "r": 120,
    "rgb": "255,140,50",
    "i": 1.8
   },
   {
    "x": 455,
    "y": 397,
    "z": 20,
    "r": 120,
    "rgb": "255,140,50",
    "i": 1.8
   },
   {
    "x": 1140,
    "y": 409,
    "z": 20,
    "r": 120,
    "rgb": "215,225,250",
    "i": 1
   },
   {
    "x": 240,
    "y": 605,
    "z": 20,
    "r": 110,
    "rgb": "255,220,160",
    "i": 1.6
   }
  ],
  "bloom": [
   0.5,
   0.4,
   0.75
  ],
  "grade": {
   "vignette": 0.5
  },
  "exposure": 1.15,
  "bg": {
   "skyTop": 460815,
   "skyBottom": 2761778,
   "haze": 3813954,
   "horizon": 668,
   "stars": 0.003,
   "grainK": 0.02,
   "glowY": 668,
   "glowColor": 1708566,
   "layers": []
  },
  "terrain": {
   "sunDir": [
    0.55,
    0.62,
    0.4
   ],
   "sunCol": [
    0.22,
    0.26,
    0.4
   ],
   "sky": [
    0.05,
    0.06,
    0.1
   ],
   "ground": [
    0.03,
    0.02,
    0.02
   ],
   "rimCol": [
    0.55,
    0.62,
    0.95
   ],
   "rimK": 0.5,
   "lipK": 0.16,
   "lipCol": [
    0.5,
    0.55,
    0.8
   ],
   "interior": 0.6,
   "bevel": 10
  },
  "moon": {
   "dx": 0.6,
   "dy": -0.8,
   "rgb": "185,195,245",
   "w": 0.75,
   "fill": "90,80,110"
  }
 },
 "palette": null,
 "actors": [
  {
   "kind": "smoke",
   "x": 862,
   "y": 447,
   "opts": {
    "pts": [
     [
      862,
      447
     ],
     [
      902,
      447
     ],
     [
      882,
      445
     ]
    ],
    "rgb": "150,140,160",
    "a": 0.3,
    "size": 7,
    "grow": 0.6
   },
   "lit": null,
   "box": [
    851,
    430,
    911,
    453
   ]
  },
  {
   "kind": "figure",
   "x": 80,
   "y": 224,
   "opts": {
    "J": {
     "legs": [
      [
       0.43,
       0.25
      ],
      [
       -0.27,
       0.06
      ]
     ],
     "weapon": "smg",
     "aim": -0.35,
     "scarf": [
      0.35,
      0.05
     ],
     "wave": 0.8
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    57,
    112,
    132,
    230
   ]
  },
  {
   "kind": "figure",
   "x": 250,
   "y": 223,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -12.649999999999999,
     "legs": [
      [
       0,
       1.27
      ],
      [
       7.59281015471359e-17,
       0.12
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       -0.1,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": 0
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    216,
    115,
    309,
    232
   ]
  },
  {
   "kind": "figure",
   "x": 382,
   "y": 223,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -12.811091270347399,
     "legs": [
      [
       0.4384062043356594,
       0.9331727983645296
      ],
      [
       -0.4384062043356594,
       0.12
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       -0.5949747468305832,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": 1.6
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    347,
    114,
    441,
    227
   ]
  },
  {
   "kind": "figure",
   "x": 514,
   "y": 223,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -13.2,
     "legs": [
      [
       0.62,
       0.12000000000000006
      ],
      [
       -0.62,
       0.12
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       -0.7999999999999999,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": 1.9594348786357652e-16
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    473,
    113,
    573,
    228
   ]
  },
  {
   "kind": "figure",
   "x": 646,
   "y": 222,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -12.811091270347399,
     "legs": [
      [
       0.43840620433565947,
       0.12
      ],
      [
       -0.4384062043356596,
       0.9331727983645294
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       -0.5949747468305833,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": -1.6
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    603,
    113,
    705,
    231
   ]
  },
  {
   "kind": "figure",
   "x": 778,
   "y": 223,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -12.649999999999999,
     "legs": [
      [
       7.59281015471359e-17,
       0.12
      ],
      [
       -1.518562030942718e-16,
       1.27
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       -0.10000000000000009,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": -3.9188697572715305e-16
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    744,
    115,
    837,
    232
   ]
  },
  {
   "kind": "figure",
   "x": 910,
   "y": 223,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -12.811091270347397,
     "legs": [
      [
       -0.4384062043356594,
       0.12
      ],
      [
       0.43840620433565936,
       0.9331727983645298
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       0.3949747468305832,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": 1.6
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    875,
    114,
    969,
    227
   ]
  },
  {
   "kind": "figure",
   "x": 1042,
   "y": 223,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -13.2,
     "legs": [
      [
       -0.62,
       0.12
      ],
      [
       0.62,
       0.12000000000000034
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       0.6,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": 5.878304635907295e-16
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    1001,
    113,
    1101,
    228
   ]
  },
  {
   "kind": "figure",
   "x": 1174,
   "y": 224,
   "opts": {
    "J": {
     "lean": 0.2,
     "hipY": -12.811091270347399,
     "legs": [
      [
       -0.4384062043356596,
       0.9331727983645294
      ],
      [
       0.43840620433565997,
       0.12
      ]
     ],
     "weapon": "pistol",
     "aim": 0.02,
     "arms": [
      [
       0.3949747468305833,
       1.1
      ]
     ],
     "scarf": [
      1.3,
      0.15
     ],
     "wave": -1.6
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    1131,
    115,
    1233,
    233
   ]
  },
  {
   "kind": "figure",
   "x": 90,
   "y": 406,
   "opts": {
    "J": {
     "legs": [
      [
       1.25,
       1.9
      ],
      [
       0.55,
       1.5
      ]
     ],
     "weapon": "smg",
     "aim": 0.3,
     "scarf": [
      0.25,
      -1.1
     ],
     "lean": -0.05
    },
    "s": 3.45,
    "accent": "#18c2b8"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": false
   },
   "box": [
    69,
    294,
    140,
    401
   ]
  },
  {
   "kind": "figure",
   "x": 290,
   "y": 389,
   "opts": {
    "J": {
     "legs": [
      [
       0.28,
       0.5
      ],
      [
       -0.12,
       0.35
      ]
     ],
     "weapon": "laser_smg",
     "aim": 0.1,
     "jet": 1.2,
     "scarf": [
      0.3,
      -1.1
     ],
     "wave": 2
    },
    "s": 3.45,
    "accent": "#18c2b8"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": false
   },
   "box": [
    267,
    279,
    348,
    397
   ]
  },
  {
   "kind": "figure",
   "x": 500,
   "y": 409,
   "opts": {
    "J": {
     "legs": [
      [
       0.06,
       0.12
      ],
      [
       -0.06,
       0.05
      ]
     ],
     "weapon": "laser_pistol",
     "aim": -0.7,
     "jet": 1.6,
     "helmet": true,
     "scarf": [
      0.7,
      0.8
     ],
     "wave": 2.8
    },
    "s": 3.45,
    "accent": "#18c2b8",
    "rot": 0.95
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": false
   },
   "box": [
    484,
    327,
    600,
    420
   ]
  },
  {
   "kind": "figure",
   "x": 700,
   "y": 389,
   "opts": {
    "J": {
     "legs": [
      [
       0.7,
       -0.25
      ],
      [
       -0.75,
       0.45
      ]
     ],
     "weapon": "smg",
     "aim": 0.9,
     "arms": [
      [
       2.7,
       0.5
      ]
     ],
     "scarf": [
      0.1,
      1.3
     ],
     "lean": -0.1
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": false
   },
   "box": [
    660,
    270,
    750,
    379
   ]
  },
  {
   "kind": "figure",
   "x": 880,
   "y": 449,
   "opts": {
    "J": {
     "hipY": -8.4,
     "legs": [
      [
       1.05,
       1.95
      ],
      [
       -0.15,
       1.35
      ]
     ],
     "lean": 0.38,
     "weapon": "smg",
     "aim": -0.25,
     "scarf": [
      0.4,
      0.9
     ]
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    840,
    356,
    937,
    453
   ]
  },
  {
   "kind": "figure",
   "x": 1080,
   "y": 449,
   "opts": {
    "J": {
     "legs": [
      [
       0.75,
       0.5
      ],
      [
       -0.55,
       0.1
      ]
     ],
     "lean": 0.25,
     "weapon": "bat",
     "aim": -0.95,
     "scarf": [
      1.1,
      0.2
     ],
     "wave": 2
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    1039,
    340,
    1122,
    455
   ]
  },
  {
   "kind": "figure",
   "x": 70,
   "y": 662,
   "opts": {
    "J": {
     "legs": [
      [
       0.62,
       0.3
      ],
      [
       -0.48,
       0.1
      ]
     ],
     "lean": 0.18,
     "arms": [
      [
       2.35,
       0.25
      ],
      [
       -0.9,
       0.5
      ]
     ],
     "scarf": [
      0.9,
      0
     ],
     "wave": 1.8
    },
    "s": 3.45,
    "accent": "#18c2b8"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    34,
    552,
    111,
    668
   ]
  },
  {
   "kind": "figure",
   "x": 250,
   "y": 677,
   "opts": {
    "J": {
     "legs": [
      [
       0.35,
       0.45
      ],
      [
       -0.25,
       0.2
      ]
     ],
     "lean": -0.45,
     "headDX": -0.6,
     "weapon": "smg",
     "aim": 1,
     "arms": [
      [
       1.6,
       0.9
      ]
     ],
     "scarf": [
      -1.5,
      -0.2
     ],
     "wave": -2
    },
    "s": 3.45,
    "accent": "#18c2b8"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    216,
    553,
    287,
    684
   ]
  },
  {
   "kind": "figure",
   "x": 470,
   "y": 664,
   "opts": {
    "J": {
     "legs": [
      [
       0.25,
       -0.35
      ],
      [
       0.6,
       0.65
      ]
     ],
     "arms": [
      [
       1.9,
       0.7
      ],
      [
       0.35,
       -0.5
      ]
     ],
     "scarf": [
      0,
      -0.6
     ],
     "wave": 0.3,
     "toe": [
      0.6,
      1.4
     ]
    },
    "s": 3.45,
    "accent": "#e8482c",
    "rot": -1.5
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": false
   },
   "box": [
    361,
    621,
    481,
    677
   ]
  },
  {
   "kind": "figure",
   "x": 640,
   "y": 662,
   "opts": {
    "J": {
     "legs": [
      [
       0.43,
       0.25
      ],
      [
       -0.27,
       0.06
      ]
     ],
     "weapon": "smg",
     "aim": -1.3962634015954636,
     "scarf": [
      0.35,
      0.05
     ],
     "wave": 0.8
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    617,
    550,
    666,
    668
   ]
  },
  {
   "kind": "figure",
   "x": 780,
   "y": 666,
   "opts": {
    "J": {
     "legs": [
      [
       0.43,
       0.25
      ],
      [
       -0.27,
       0.06
      ]
     ],
     "weapon": "smg",
     "aim": -0.6981317007977318,
     "scarf": [
      0.35,
      0.05
     ],
     "wave": 0.8
    },
    "s": 3.45,
    "accent": "#18c2b8"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    757,
    554,
    825,
    672
   ]
  },
  {
   "kind": "figure",
   "x": 920,
   "y": 674,
   "opts": {
    "J": {
     "legs": [
      [
       0.43,
       0.25
      ],
      [
       -0.27,
       0.06
      ]
     ],
     "weapon": "smg",
     "aim": 0,
     "scarf": [
      0.35,
      0.05
     ],
     "wave": 0.8
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    897,
    562,
    975,
    680
   ]
  },
  {
   "kind": "figure",
   "x": 1060,
   "y": 662,
   "opts": {
    "J": {
     "legs": [
      [
       0.43,
       0.25
      ],
      [
       -0.27,
       0.06
      ]
     ],
     "weapon": "smg",
     "aim": 0.6981317007977318,
     "scarf": [
      0.35,
      0.05
     ],
     "wave": 0.8
    },
    "s": 3.45,
    "accent": "#18c2b8"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    1037,
    550,
    1103,
    668
   ]
  },
  {
   "kind": "figure",
   "x": 1200,
   "y": 673,
   "opts": {
    "J": {
     "legs": [
      [
       0.43,
       0.25
      ],
      [
       -0.27,
       0.06
      ]
     ],
     "weapon": "smg",
     "aim": 1.3962634015954636,
     "scarf": [
      0.35,
      0.05
     ],
     "wave": 0.8
    },
    "s": 3.45,
    "accent": "#e8482c"
   },
   "lit": {
    "size": 1.6,
    "halo": null,
    "shadow": true
   },
   "box": [
    1177,
    548,
    1230,
    679
   ]
  }
 ],
 "fx": [],
 "hud": null,
 "labels": [
  {
   "text": "I D L E",
   "x": 80,
   "y": 250,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   1 / 8",
   "x": 250,
   "y": 249,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   2 / 8",
   "x": 382,
   "y": 249,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   3 / 8",
   "x": 514,
   "y": 249,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   4 / 8",
   "x": 646,
   "y": 248,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   5 / 8",
   "x": 778,
   "y": 249,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   6 / 8",
   "x": 910,
   "y": 249,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   7 / 8",
   "x": 1042,
   "y": 249,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "R U N   8 / 8",
   "x": 1174,
   "y": 250,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "J U M P",
   "x": 90,
   "y": 476,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "J E T P A C K",
   "x": 290,
   "y": 475,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "S P A C E   T H R U S T   ·   H E L M E T",
   "x": 500,
   "y": 475,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "F A L L",
   "x": 700,
   "y": 475,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "L A N D",
   "x": 880,
   "y": 475,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "M E L E E   S W I N G",
   "x": 1080,
   "y": 475,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "T H R O W",
   "x": 70,
   "y": 688,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "H I T   R E A C T I O N",
   "x": 250,
   "y": 703,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "D E A T H   /   R A G D O L L",
   "x": 430,
   "y": 690,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "A I M   - 8 0 °",
   "x": 640,
   "y": 688,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "A I M   - 4 0 °",
   "x": 780,
   "y": 692,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "A I M   0 °",
   "x": 920,
   "y": 700,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "A I M   + 4 0 °",
   "x": 1060,
   "y": 688,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "A I M   + 8 0 °",
   "x": 1200,
   "y": 699,
   "font": "11px Georgia, serif",
   "fill": "rgba(225,218,230,0.72)",
   "align": "center"
  },
  {
   "text": "M23 stick figure — pose sheet at 3× (F4 proportions). The scarf lags the motion; the helmet + team visor replaces the spacesuit.",
   "x": 24,
   "y": 34,
   "font": "italic 15px Georgia, serif",
   "fill": "rgba(225,218,230,0.78)",
   "align": "left"
  }
 ]
}
