import { PNG } from 'pngjs'
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative, basename } from 'node:path'

const ROOT = process.argv[2] ?? new URL('../../sprite_packs', import.meta.url).pathname
const walk = (d) => readdirSync(d).flatMap((n) => {
  const p = join(d, n)
  return statSync(p).isDirectory() ? walk(p) : p.endsWith('.png') ? [p] : []
})

function measure(file) {
  const p = PNG.sync.read(readFileSync(file))
  let minX = p.width, minY = p.height, maxX = -1, maxY = -1, opaque = 0, semi = 0
  for (let y = 0; y < p.height; y++) for (let x = 0; x < p.width; x++) {
    const a = p.data[((p.width * y + x) << 2) + 3]
    if (a > 128) { opaque++; if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y }
    else if (a > 16) semi++
  }
  const bw = maxX < 0 ? 0 : maxX - minX + 1, bh = maxY < 0 ? 0 : maxY - minY + 1
  return { w: p.width, h: p.height, bw, bh,
    fill: bw * bh ? opaque / (bw * bh) : 0,       // how solid inside its own bounds
    soft: opaque ? semi / opaque : 0 }             // wispy edges → bad terrain stamp
}

const packs = readdirSync(ROOT).filter((n) => statSync(join(ROOT, n)).isDirectory())
const summary = []
for (const pack of packs) {
  const files = walk(join(ROOT, pack)).sort()
  const rows = files.map((f) => ({ rel: relative(join(ROOT, pack), f), ...measure(f) }))
  const groups = new Map()
  for (const r of rows) {
    const g = r.rel.includes('/') ? r.rel.slice(0, r.rel.lastIndexOf('/')) : '(top level)'
    if (!groups.has(g)) groups.set(g, [])
    groups.get(g).push(r)
  }
  const avg = (a, k) => a.reduce((s, r) => s + r[k], 0) / a.length
  let md = `# ${pack}\n\n${rows.length} PNG files. Generated by \`scripts/catalogue-sprites.mjs\`.\n\n`
  md += `**Columns.** \`bounds\` is the opaque bounding box — the real size of the object, `
  md += `not the canvas. \`fill\` is the fraction of that box which is opaque (α>128): high means `
  md += `a solid blob that stamps into the terrain mask cleanly, low means a sparse shape with `
  md += `holes. \`soft\` is semi-transparent pixels (16<α≤128) as a fraction of opaque ones — `
  md += `a wispy edge that thresholds badly.\n\n`
  for (const [g, rs] of [...groups].sort()) {
    md += `## ${g}\n\n`
    md += `${rs.length} files · mean bounds ${Math.round(avg(rs,'bw'))}×${Math.round(avg(rs,'bh'))} · `
    md += `mean fill ${avg(rs,'fill').toFixed(2)} · mean soft ${avg(rs,'soft').toFixed(2)}\n\n`
    md += `| file | canvas | bounds | fill | soft |\n|---|---|---|---|---|\n`
    for (const r of rs) md += `| \`${basename(r.rel)}\` | ${r.w}×${r.h} | ${r.bw}×${r.bh} | ${r.fill.toFixed(2)} | ${r.soft.toFixed(2)} |\n`
    md += `\n`
  }
  writeFileSync(join(ROOT, pack, 'CATALOGUE.md'), md)
  summary.push({ pack, n: rows.length, bw: avg(rows,'bw'), bh: avg(rows,'bh'), fill: avg(rows,'fill'), soft: avg(rows,'soft') })
}
console.log('pack        n   mean-bounds   fill  soft')
for (const s of summary) console.log(`${s.pack.padEnd(10)} ${String(s.n).padStart(3)}   ${String(Math.round(s.bw)).padStart(4)}×${String(Math.round(s.bh)).padEnd(4)}   ${s.fill.toFixed(2)}  ${s.soft.toFixed(2)}`)
