/**
 * T21.28: decorations on real maps, generated by the compiled `game-core`.
 *
 * The coordinator's rulings, as assertions: a decoration is drawn only with rock
 * under every column of its **art's** base; the generator chooses spots where that
 * holds, against one conservative width (`DECOR_BASE_W`) that the atlas must never
 * exceed; and on nine maps each draws **at least 90 %** of what the rule it replaced
 * drew (the first version, choosing from the whole surface, drew 40 of 96).
 *
 * The **old rule is re-stated here as the instrument**, not imported: it no longer
 * exists in `decorations-math.ts`, and the comparison is the point.
 */
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { PNG } from 'pngjs'
import { Core, MapScale } from '../core/index'
import { constants } from '../../../scripts/lib/rust-constants.mjs'
import {
  baseColumns,
  decodeFlags,
  fromMeta,
  opaqueBase,
  place,
  DECOR_GROUND_SLACK_PX,
  SCALE_TIERS,
  type ArtBase,
} from './decorations-math'

const here = dirname(fileURLToPath(import.meta.url))
const wasmBytes = readFileSync(join(here, '../core/pkg/game_wasm_bg.wasm'))
const atlasDir = join(here, '../../../assets/atlas')
const atlas = JSON.parse(readFileSync(join(atlasDir, 'decor.json'), 'utf8')) as {
  frames: Record<string, { frame: { x: number; y: number; w: number; h: number } }>
  meta?: { image?: string }
}
const png = PNG.sync.read(readFileSync(join(atlasDir, atlas.meta?.image ?? 'decor.png')))

/** Each frame's base, through the same `opaqueBase` the game uses, on the PNG's alpha. */
const bases = new Map<string, ArtBase | null>()
function baseOf(f: string): ArtBase | null {
  const fr = atlas.frames[f]?.frame
  if (!fr) return null
  if (!bases.has(f)) {
    bases.set(
      f,
      opaqueBase((x, y) => png.data[((fr.y + y) * png.width + fr.x + x) * 4 + 3] ?? 0, fr.w, fr.h),
    )
  }
  return bases.get(f) ?? null
}

/** The pre-T21.28 rule: 3 solid pixels anywhere in a 16 px span one row down. */
function oldSupported(x: number, y: number, solidAt: (x: number, y: number) => boolean) {
  let solid = 0
  for (let dx = -8; dx < 8; dx++) if (solidAt(x + dx, y + 1) && ++solid >= 3) return true
  return false
}

describe('decorations on real maps (T21.28)', () => {
  it('the atlas never draws a base wider than DECOR_BASE_W, and both sides share the slack', () => {
    const k = constants()
    const widestTier = Math.max(...SCALE_TIERS)
    for (const f of Object.keys(atlas.frames)) {
      const b = baseOf(f)
      if (!b) continue
      // Symmetric extent: the generator seats a window centred on the anchor.
      const extent = 2 * Math.max(b.frameW / 2 - b.left, b.right - b.frameW / 2) * widestTier
      expect(extent, `${f}: base extent at the widest tier`).toBeLessThanOrEqual(k.get('DECOR_BASE_W'))
    }
    expect(DECOR_GROUND_SLACK_PX).toBe(k.get('DECOR_GROUND_SLACK'))
  })

  it('draws at least 90 % of what the old rule drew on every map, every one fully seated', async () => {
    const core = await Core.init(wasmBytes)
    const rows: string[] = []
    for (const seed of [1n, 4242n, 31337n]) {
      for (const scale of [MapScale.Small, MapScale.Medium, MapScale.Large]) {
        core.generate(seed, scale)
        const wire = fromMeta(core.meta.decorations)
        const solidAt = (x: number, y: number) => core.solidAt(x, y)
        const before = wire.filter((d) => baseOf(`decor_${d.kind}`) && oldSupported(d.x, d.y, solidAt)).length
        const drawn = place(wire, baseOf, solidAt)
        rows.push(`${seed}/${scale}: ${wire.length} generated, ${before} drawn by the old rule, ${drawn.length} now`)
        expect(drawn.length, `${seed}/${scale}`).toBeGreaterThanOrEqual(Math.ceil(0.9 * before))
        // Every drawn prop re-checked here, column by column, against the mask.
        for (const d of drawn) {
          const base = baseOf(d.frame)!
          const { scale: s, flip } = decodeFlags(wire.find((w) => w.x === d.x && w.y === d.y && w.kind === d.kind)!.flags)
          const { x0, x1 } = baseColumns(d.x, base, s, flip)
          for (let col = x0; col < x1; col++) {
            const seated = [1, 2, 3].slice(0, DECOR_GROUND_SLACK_PX + 1).some((dy) => solidAt(col, d.y + dy))
            expect(seated, `${seed}/${scale}: ${d.frame} at (${d.x}, ${d.y}) column ${col} over air`).toBe(true)
          }
        }
      }
    }
    console.log(`T21.28 DECOR ${rows.join(' | ')}`)
  }, 120_000)
})
